name: Deploy Container App

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_app_container.yml'
      - 'container_app/**'
      - 'shared/**'
      - 'Dockerfile.app'

env:
  AWS_REGION: us-west-2
  AWS_ECR_REPO: apps/serverless-inference
  AWS_ROLE_TO_ASSUME: arn:aws:iam::650251730947:role/GitActionsLambdaRole

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Container App
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActionsContainerAppDeployment

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ env.AWS_ECR_REPO }}
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfile.app .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v2
      with:
        task-definition: serverless-inference-fargate-task-definition.json 
        container-name: ServerlessInferenceFargateContainer
        image: ${{ steps.login-ecr.outputs.registry }}/${{ env.AWS_ECR_REPO }}:latest    
    
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ServerlessInferenceFargateService
        cluster: GoldRushCluster
        wait-for-service-stability: true
